PicsMapWeb/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PicsMapWeb.Models;
using System.Web.Helpers;
using System.IO;

namespace PicsMapWeb.Controllers
{
    public class PhotoController : Controller
    {
        public class ShowPhotoModel
        {
            public int idPhoto { get; set; }
            public int idCpt { get; set; }
        }
        //
        // GET: /Photo/
        public ViewResult Show(ShowPhotoModel model)
        {
            int idPhoto = model.idPhoto;
            int idCpt = model.idCpt;

            DataAccess.Membership cpt = BusinessManagement.Compte.findByLogin(User.Identity.Name);
            
            ViewBag.cptName = cpt.Nom;
            ViewBag.cptFirstname = cpt.Prenom;
            ViewBag.cptLogin = cpt.Login;
            ViewBag.cptEmail = cpt.Email;

            DataAccess.Photo currentPhoto = BusinessManagement.Photo.findById(idPhoto);
            ViewBag.currentPhoto = currentPhoto;

            DataAccess.Membership cptCurrentPhotoAuthor = BusinessManagement.Compte.findById(idCpt);
            ViewBag.currentPhotoAuthor = cptCurrentPhotoAuthor;

            List<DataAccess.Photo> currentAuthorListPhotos = new List<DataAccess.Photo>();
            currentAuthorListPhotos = BusinessManagement.Photo.findForAccount(0, 10, cptCurrentPhotoAuthor.Login);
            ViewBag.photosList = currentAuthorListPhotos;            
            /*
            List<DataAccess.Photo> myListPhotos = new List<DataAccess.Photo>();
            myListPhotos = BusinessManagement.Photo.findForAccount(0,10, cpt.Login);
            ViewBag.photosList = myListPhotos;

            List<DataAccess.Photo> listFriendsPhotos = new List<DataAccess.Photo>();
            listFriendsPhotos = BusinessManagement.Photo.findAllFriendPictures(0, 10, cpt.Login);          
            ViewBag.friendPhotosList = listFriendsPhotos;

            List<DataAccess.Photo> listRecentFriendsPhotos = new List<DataAccess.Photo>();
            listRecentFriendsPhotos = BusinessManagement.Photo.findRecentFriendPhoto(0, 10, cpt.Login, DateTime.Now.AddDays(-3));
            ViewBag.friendsRecentPhotosList = listRecentFriendsPhotos;

            List<DataAccess.Photo> listRecentPhotos = new List<DataAccess.Photo>();
            listRecentPhotos = BusinessManagement.Photo.findLastPhoto(0, 10, DateTime.Now.AddDays(-3));
            ViewBag.recentPhotosList = listRecentPhotos;
            */

            // attention offset et index inversés !
            List<DataAccess.Commentaire> listLastComments = new List<DataAccess.Commentaire>();
            listLastComments = BusinessManagement.Commentaire.findComments(30, 0, idPhoto);
            
            List<CommentListModel> lComment = new List<CommentListModel>();
            foreach (DataAccess.Commentaire comm in listLastComments) {
                lComment.Add(new CommentListModel() {
                    Id = comm.Id,
                    authFirstname = comm.Membership.Prenom,
                    authName = comm.Membership.Nom,
                    date = comm.Date.Value,
                    Texte = comm.Texte,
                    IdCpt = comm.cpt_Id,
                    PhotoUserProfil = comm.Membership.Photo_Profil
                });
            }
            ViewBag.lastCommentsList = lComment;

            // Modifier l'id de la photo, par défaut = 1
            double noteMoyenne = BusinessManagement.Evaluation.findEvalsForPicture(idPhoto);
            if (Double.IsNaN(noteMoyenne))
                noteMoyenne = 0;
            ViewBag.noteMoyennePhoto = noteMoyenne;
            ViewBag.noteClasses = String.Format("note note_{0}", noteMoyenne);

            ViewBag.isEvaluated = BusinessManagement.Evaluation.hasEvaluate(idPhoto, cpt.Login);
            //deleteEval(long photoId, string login)
            //findCommentsForPicture(long photoId)

            List<DataAccess.Photo> PhotosCopy = new List<DataAccess.Photo>();


            DataAccess.Photo p = new DataAccess.Photo();
            p.Titre = currentPhoto.Titre;
            p.longitude = currentPhoto.longitude;
            p.latitude = currentPhoto.latitude;
            p.Url = currentPhoto.Url;
            PhotosCopy.Add(p);


            System.Web.Script.Serialization.JavaScriptSerializer oSerializer =
            new System.Web.Script.Serialization.JavaScriptSerializer();
            string sJSON = oSerializer.Serialize(PhotosCopy);
            ViewBag.markerListJS = sJSON;

            return View();
        }

        [HttpPost]
        public ActionResult Show(CommentModel model)
        {
            DataAccess.Membership cpt = BusinessManagement.Compte.findByLogin(User.Identity.Name);

            if (ModelState.IsValid)
            {
                try
                {
                    BusinessManagement.Commentaire.createComment(model.IdPhoto, model.Texte, cpt.Login);

                    return Show(new ShowPhotoModel() { idPhoto = model.IdPhoto, idCpt = model.IdAuthor });
                }
                catch (BusinessManagement.BusinessManagementException e)
                {
                    ModelState.AddModelError("", e.Message);
                }
            }

            // If we got this far, something failed, redisplay form
            return Show(new ShowPhotoModel() { idPhoto = model.IdPhoto, idCpt = model.IdAuthor });
        }

        public ActionResult DoEval1Star(int idPhoto)
        {
            DataAccess.Membership cpt = BusinessManagement.Compte.findByLogin(User.Identity.Name);

            ViewBag.cptName = cpt.Nom;
            ViewBag.cptFirstname = cpt.Prenom;
            ViewBag.cptLogin = cpt.Login;
            ViewBag.cptEmail = cpt.Email;

            BusinessManagement.Evaluation.createEval(idPhoto, cpt.Login, 1);

            return RedirectToAction("Show", new { idPhoto = idPhoto, idCpt = cpt.Id });
            
        }

        public ActionResult DoEval2Star(int idPhoto)
        {
            DataAccess.Membership cpt = BusinessManagement.Compte.findByLogin(User.Identity.Name);

            ViewBag.cptName = cpt.Nom;
            ViewBag.cptFirstname = cpt.Prenom;
            ViewBag.cptLogin = cpt.Login;
            ViewBag.cptEmail = cpt.Email;

            BusinessManagement.Evaluation.createEval(idPhoto, cpt.Login, 2);

            return RedirectToAction("Show", new { idPhoto = idPhoto, idCpt = cpt.Id });
        }

        public ActionResult DoEval3Star(int idPhoto)
        {
            DataAccess.Membership cpt = BusinessManagement.Compte.findByLogin(User.Identity.Name);

            ViewBag.cptName = cpt.Nom;
            ViewBag.cptFirstname = cpt.Prenom;
            ViewBag.cptLogin = cpt.Login;
            ViewBag.cptEmail = cpt.Email;

            BusinessManagement.Evaluation.createEval(idPhoto, cpt.Login, 3);

            return RedirectToAction("Show", new { idPhoto = idPhoto, idCpt = cpt.Id });
        }

        public ActionResult DoEval4Star(int idPhoto)
        {
            DataAccess.Membership cpt = BusinessManagement.Compte.findByLogin(User.Identity.Name);

            ViewBag.cptName = cpt.Nom;
            ViewBag.cptFirstname = cpt.Prenom;
            ViewBag.cptLogin = cpt.Login;
            ViewBag.cptEmail = cpt.Email;

            BusinessManagement.Evaluation.createEval(idPhoto, cpt.Login, 4);

            return RedirectToAction("Show", new { idPhoto = idPhoto, idCpt = cpt.Id });
        }

        public ActionResult DoEval5Star(int idPhoto)
        {
            DataAccess.Membership cpt = BusinessManagement.Compte.findByLogin(User.Identity.Name);

            ViewBag.cptName = cpt.Nom;
            ViewBag.cptFirstname = cpt.Prenom;
            ViewBag.cptLogin = cpt.Login;
            ViewBag.cptEmail = cpt.Email;

            BusinessManagement.Evaluation.createEval(idPhoto, cpt.Login, 5);

            return RedirectToAction("Show", new { idPhoto = idPhoto, idCpt = cpt.Id });
        }
        public ActionResult DeleteEval(int idPhoto)
        {
            DataAccess.Membership cpt = BusinessManagement.Compte.findByLogin(User.Identity.Name);

            ViewBag.cptName = cpt.Nom;
            ViewBag.cptFirstname = cpt.Prenom;
            ViewBag.cptLogin = cpt.Login;
            ViewBag.cptEmail = cpt.Email;

            // Modifier l'id de la photo, par défaut = 1
            BusinessManagement.Evaluation.deleteEval(idPhoto, cpt.Login);

            return RedirectToAction("Show", new { idPhoto = idPhoto, idCpt = cpt.Id });
        }

        public ViewResult DeleteComment(int commentId)
        {
            DataAccess.Membership cpt = BusinessManagement.Compte.findByLogin(User.Identity.Name);

            ViewBag.cptName = cpt.Nom;
            ViewBag.cptFirstname = cpt.Prenom;
            ViewBag.cptLogin = cpt.Login;
            ViewBag.cptEmail = cpt.Email;

            BusinessManagement.Commentaire.deleteComment(commentId);

            return View("Show");

        }

        
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(PhotoModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    DataAccess.Photo photo = new DataAccess.Photo();
                    photo.Titre = model.Title;
                    photo.Description = model.Description;
                    photo.date_Poste = DateTime.Now;
                    photo.accept = true;
                    photo.latitude = double.Parse(model.latitude, System.Globalization.CultureInfo.CreateSpecificCulture("en"));
                    photo.longitude = double.Parse(model.longitude, System.Globalization.CultureInfo.CreateSpecificCulture("en"));

                    // Gestion de l'image
                    var webHelper = new Helpers.WebImageHelper();
                    var image = webHelper.GetImageFromRequest();

PicsMapWeb/Views/Photo/Add.cshtml
@model PicsMapWeb.Models.PhotoModel

@{
    ViewBag.Title = "Add";
}




<div id="content_map">
    <ul class="map_title">
        <li><strong>Choississez la localisation de votre photo en mettant la puce rouge au bon endroit</strong></li>
    </ul>
    <div id="mapCanvas"></div>
</div>

<div id="infoPanel">
    <b>Marker status:</b>
    <div id="markerStatus"><i>Click and drag the marker.</i></div>
    <b>Current position:</b>
    <div id="info"></div>
    <b>Closest matching address:</b>
    <div id="address"></div>
</div>

<div class="content_list">
    <h1>Informations sur votre nouvelle photo</h1>


    @using (Html.BeginForm("Add", "Photo", FormMethod.Post, new { enctype = "multipart/form-data" })) {
    <div class="content_add_photo">
        @Html.ValidationSummary(true, "Echec de la création du compte. Corrigez les erreurs et recommencez.", new {@style = "color:red;"})
        <div>
            <input type="file" value="Choisir une photo" name="photo"/>
        </div>

        <div>
            @Html.LabelFor(m => m.Title) * 
            @Html.ValidationMessageFor(m => m.Title, null, new { @style = "color:red;" })
        </div>
        <div>
            @Html.TextBoxFor(m => m.Title, new { @maxlength = 50 })
        </div>

        <div>
            @Html.LabelFor(m => m.Description) * 
            @Html.ValidationMessageFor(m => m.Description, null, new { @style = "color:red;" })
        </div>
        <div>
            @Html.TextBoxFor(m => m.Description, new { @maxlength = 140 })
        </div>

        <div>
            @Html.LabelFor(m => m.Tags) 
            @Html.ValidationMessageFor(m => m.Tags, null, new { @style = "color:red;" })
        </div>
        <div>
            @Html.TextBoxFor(m => m.Tags)
        </div>

        @Html.HiddenFor(m => m.latitude, new { @id = "latitude" })
        @Html.ValidationMessageFor(m => m.latitude, null, new { @style = "color:red;" })
        @Html.HiddenFor(m => m.longitude, new { @id = "longitude" })
        @Html.ValidationMessageFor(m => m.longitude, null, new { @style = "color:red;" })

        <div>
            <input class="input_submit" type="submit" value="Envoyer" />
        </div>
    </div>
    }

</div>

PicsMapWeb/Views/Photo/Show.cshtml
@model PicsMapWeb.Models.CommentModel

@{
    ViewBag.Title = "Show";
}

<script type="text/javascript">
var markers = @Html.Raw(ViewBag.markerListJS);
var photos = @Html.Raw(ViewBag.markerListJS);
updateClusterMap();
</script>

<h1><a href="/Account/Show/?idCpt=@ViewBag.currentPhotoAuthor.Id">@ViewBag.currentPhotoAuthor.Prenom @ViewBag.currentPhotoAuthor.Nom</a> > @ViewBag.currentPhoto.Titre</h1>
<div class="content_photo_display">
	<img class="photo_display" src="@ViewBag.currentPhoto.Url" />
	<ul>
		<li class="new_com">
            
            @using (Html.BeginForm())
            {
                //@using (Ajax.BeginForm("Show", new AjaxOptions { UpdateTargetId = "body" }))
                    @Html.TextBoxFor(m => m.Texte, new { @Value = "Ajouter un commentaire...", @onclick = "clickclear(this,'Ajouter un commentaire...')" })
                    @Html.HiddenFor(m => m.IdPhoto, new { @Value = @ViewBag.currentPhoto.Id });
                    @Html.HiddenFor(m => m.IdAuthor, new { @Value = @ViewBag.currentPhotoAuthor.Id });

            }
        </li>
        @if (ViewBag.lastCommentsList != null)
        {
            foreach (var item in @ViewBag.lastCommentsList)
            {
                <li>
			        <img src="@item.PhotoUserProfil" />
			        <p><a href="/Account/Show/?idCpt=@item.IdCpt">@item.authFirstname @item.authName</a> @item.Texte</p>
		        </li>
            }
        }
        else
        {
            <li>
			    <p>Aucun commentaire a afficher...</p>
		    </li>
        }
	</ul>
</div>
<div id="content_footer">&nbsp;</div>
			
<!-- photo detail content -->
<h1>Zoom sur  @ViewBag.currentPhoto.Titre</h1>
<div class="content_photo_detail">
	<div class="content_photo_map">
		<div id="map" style="width:450px;height:250px;"></div>
	</div>
	<div class="content_photo_info">
		<div>
			<strong>Informations</strong>
            @if (@ViewBag.isEvaluated == false)
            {
				<a href="@Url.Action("DoEval1Star", new { idPhoto = @ViewBag.currentPhoto.Id })"><img src="@Url.Content("~/Content/i/star.png")"/></a>
				<a href="@Url.Action("DoEval2Star", new { idPhoto = @ViewBag.currentPhoto.Id })"><img src="@Url.Content("~/Content/i/star.png")"/></a>
				<a href="@Url.Action("DoEval3Star", new { idPhoto = @ViewBag.currentPhoto.Id })"><img src="@Url.Content("~/Content/i/star.png")"/></a>
				<a href="@Url.Action("DoEval4Star", new { idPhoto = @ViewBag.currentPhoto.Id })"><img src="@Url.Content("~/Content/i/star.png")"/></a>
				<a href="@Url.Action("DoEval5Star", new { idPhoto = @ViewBag.currentPhoto.Id })"><img src="@Url.Content("~/Content/i/star.png")"/></a>
            }
            else
            {
                <div class="content_note">
                    <div class="@ViewBag.noteClasses"></div>
                    @Html.ActionLink("Supprimer votre évaluation", "DeleteEval", new { idPhoto = @ViewBag.currentPhoto.Id })
                </div>
            }
		</div>
		<div class="list_info">
			<div class="list_info_key">
				<p>Nom de la photo:</p>
				<p>Description:</p>
				<p>Auteur:</p>
				<p>Date d'ajout:</p>
			</div>
			<div class="list_info_value">
				<p> @ViewBag.currentPhoto.Titre</p>
				<p> @ViewBag.currentPhoto.Description</p>
				<p> @ViewBag.currentPhotoAuthor.Login</p>
				<p> @ViewBag.currentPhoto.date_Poste</p>
			</div>
		</div>
        <div class="fb-like margin_top_10" data-href="http://localhost:5503" data-send="false" data-width="350" data-show-faces="false" data-font="segoe ui"></div>
	</div>
</div>
<div id="content_footer">&nbsp;</div>
			
<h1><a href="/Account/Show/?idCpt=@ViewBag.currentPhotoAuthor.Id">@ViewBag.currentPhotoAuthor.Prenom @ViewBag.currentPhotoAuthor.Nom</a> > Liste de photos</h1>
<div class="content_user_photo_list">
	<div class="content_list_photo">
            @if (ViewBag.photosList != null)
            {
                foreach (var item in @ViewBag.photosList)
                {
                   <a href="/Photo/Show/?idPhoto=@item.Id&idCpt=@item.cpt_Id"><img src="@item.Url" alt="" /></a>
                }
            }
            else
            { 
			    <p>Aucune photo à afficher.</p>
            }
	</div>
</div>

PicsMapWeb/Views/Photo/_backupShow.cshtml
@model PicsMapWeb.Models.CommentModel

@{
    ViewBag.Title = "Show";
}

<h2>Show Photo</h2>
<p>Show d'une photo: avec la photo en grand, commentaire sur la droite, info sur la photo en bas (carte + titre, description... + bouton like)</p>
<p>Nom: @ViewBag.cptName</p>
<p>Prénom: @ViewBag.cptFirstname</p>
<p>Login: @ViewBag.cptLogin</p>
<p>Email: @ViewBag.cptEmail</p>


<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true, "Comment creation was unsuccessful. Please correct the errors and try again.")
    <div>
        <fieldset>
            <legend>Comment Information</legend>

            <div class="editor-field">
                @Html.TextBoxFor(m => m.Texte)
                @Html.ValidationMessageFor(m => m.Texte)
            </div>

            <p>
                <input type="submit" value="AddComment" />
            </p>
        </fieldset>
    </div>
}

<table>
    <tr>
        <td>Liste des 5 derniers commentaires de la photo 1</td>
    </tr>
    @if (ViewBag.lastCommentsList != null)
    {
        foreach (var item in @ViewBag.lastCommentsList)
        {
        <tr>
            <td>@item.Texte<br /></td>
            <td>@item.Date<br /></td>
            <td>@Html.ActionLink("Delete", "doDelete", new { commentId = item.Id })</td>
        </tr>
        }
    }
</table>
<br /><br />

<table>
    <tr>
        <td>Ma liste de photos</td>
    </tr>
    @if (ViewBag.photosList != null)
    {
        foreach (var item in @ViewBag.photosList)
        {
        <tr>
            <td>@item.Titre<br /></td>
            <td><a href="@Url.Action("DoEval", new { idPhoto = item.Id })"><img src="@item.Url" height="150" width="250" alt="" /></a><br /></td>
            <td>@item.date_Poste<br /></td>
            <td>@Html.ActionLink("Evaluer une photo", "DoEval", new { idPhoto = item.Id })</td>
            <td>@Html.ActionLink("Supprimer une évaluation", "DeleteEval", new { idPhoto = item.Id })</td>
            <td>Note moyenne de la photo id=1
                @if (ViewBag.noteMoyennePhoto != null)
                {
                    @ViewBag.noteMoyennePhoto
                }
            </td>
        </tr>
        }
    }
</table>
<br /><br />

<table>
    <tr>
        <td>Liste des photos de mes amis</td>
    </tr>
    @if (ViewBag.friendPhotosList != null)
    {
        foreach (var item in @ViewBag.friendPhotosList)
        {

        <tr>
            <td>@item.Titre<br /></td>
            <td><img src="@item.Url" height="150" width="250" alt="" /><br /></td>
            <td>@item.date_Poste<br /></td>
        </tr>
        }
    }
</table>
<br /><br />

<table>
    <tr>
        <td>Liste des récentes photos de mes amis (datant de moins de 3 jours)</td>
    </tr>
    @if (ViewBag.friendsRecentPhotosList != null)
    {
        foreach (var item in @ViewBag.friendsRecentPhotosList)
        {

        <tr>
            <td>@item.Titre<br /></td>
            <td><img src="@item.Url" height="150" width="250" alt="" /><br /></td>
            <td>@item.date_Poste<br /></td>
        </tr>
        }
    }
</table>
<br /><br />

<table>
    <tr>
        <td>Liste des dernières photos postées (datant de moins de 3 jours)</td>
    </tr>
    @if (ViewBag.recentPhotosList != null)
    {
        foreach (var item in @ViewBag.recentPhotosList)
        {

        <tr>
            <td>@item.Titre<br /></td>
            <td><img src="@item.Url" height="150" width="250" alt="" /><br /></td>
            <td>@item.date_Poste<br /></td>
        </tr>
        }
    }
</table>

<img src="@Url.Content("~/Content/images/building.JPG")" />